config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'signup', to: 'users#new', as: 'signup'
  get 'delete', to: 'users#delete', as: 'delete_users'
  post 'destroy', to: 'users#destroy', as: 'destroy_users'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get '/password/reset', to: 'password_resets#new'
  post '/password/reset', to: 'password_resets#create'
  get '/password/reset/edit', to: 'password_resets#edit'
  patch '/password/reset/edit', to: 'password_resets#update'
  
  resources :users
  resources :sessions

  root 'contacts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    require "cpf_cnpj"
    before_save :validate_cpf
    belongs_to :user
    validates :name, presence: true
    validates :phone_number, presence: true
    validates :cep, presence: true
    validates :address, presence: true
    validates :cpf, presence: true, uniqueness: true
    
    def validate_cpf
        unless CPF.valid?(self.cpf)
          errors.add(:cpf, "CPF inválido")
          throw :abort
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: true

    has_many :contacts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Não autorizado. Realize o login." unless current_user
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authorize, only: [:index, :show, :new, :edit, :update, :destroy, :create]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all.order(:name)
    if params[:search].present?
      search_term = params[:search].downcase
      @contacts = @contacts.where("LOWER(name) LIKE ? OR LOWER(cpf) LIKE ?", "%#{search_term}%", "%#{search_term}%")
    end  
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user    

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :cpf, :phone_number, :cep, :address, :lat, :lng)
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    if @user = User.find_by(email: params[:email_address])
      PasswordMailer.with(user: @user).reset.deliver_later
    end
    redirect_to '/login', notice: 'Se o e-mail informado estiver correto, um link será enviado para redefinir sua senha.'
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to '/login', alert: 'Seu token expirou. Favor tentar novamente.'
  end

  def update
  @user = User.find_signed!(params[:token], purpose: 'password_reset')
  if @user.update(password_params)
    redirect_to '/login', notice: 'Senha alterada com sucesso.'
  else
    render 'edit'
  end
  rescue ActiveSupport::MessageVerifier::InvalidSignature
  redirect_to '/login', alert: 'Seu token expirou. Favor tentar novamente.'
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logado com sucesso!"
    else
      flash.now[:alert] = "Email ou senha inválidos"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Deslogado com sucesso!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save!
        session[:user_id] = @user.id
        redirect_to root_url, notice: "Registrado com sucesso!"
      else
        render :new
      end
  end

  def delete
  end

  def destroy
    user = current_user
    if user && user.authenticate(params[:password])
      current_user.destroy
      session[:user_id] = nil
      redirect_to signup_path, notice: "Sua conta foi excluída com sucesso."
    else
      redirect_to root_url, alert: "Senha incorreta. Por favor, tente novamente."
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep, onblur: "pesquisacep(this.value);" %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
    <input type="button" value="Verificar lat/lng" onclick="codeAddress()">
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :neighborhood %>
    <%= form.text_field :neighborhood %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script> 
    function limpa_formulário_cep() {
            //Limpa valores do formulário de cep.
            document.getElementById('contact_address').value=("");
            document.getElementById('contact_neighborhood').value=("");
            document.getElementById('contact_city').value=("");
            document.getElementById('contact_state').value=("");
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('contact_address').value=(conteudo.logradouro);
            document.getElementById('contact_neighborhood').value=(conteudo.bairro);
            document.getElementById('contact_city').value=(conteudo.localidade);
            document.getElementById('contact_state').value=(conteudo.uf);
        } //end if.
        else {
            //CEP não Encontrado.
            limpa_formulário_cep();
            alert("CEP não encontrado.");
        }
    }
        
    function pesquisacep(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if(validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('contact_address').value="...";
                document.getElementById('contact_neighborhood').value="...";
                document.getElementById('contact_city').value="...";
                document.getElementById('contact_state').value="...";

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = 'https://viacep.com.br/ws/'+ cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);

            } //end if.
            else {
                //cep é inválido.
                limpa_formulário_cep();
                alert("Formato de CEP inválido.");
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    };

</script>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<%= form_tag contacts_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder: "Buscar por nome ou CPF" %>
  <%= submit_tag "Buscar" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Phone number</th>
      <th>Cep</th>
      <th>Address</th>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="contacts">
    <% @contacts.each do |contact| %>
      <tr id=<%= contact.id %>>
        <td><a href="javascript:;" id=<%= contact.id %> class="btn-center-map" data-lat=<%= contact.lat %> data-lng=<%= contact.lng %>><%= contact.name %></a></td>
        <td><%= contact.cpf %></td>
        <td><%= contact.phone_number %></td>
        <td><%= contact.cep %></td>
        <td><%= contact.address %></td>
        <td class="lat"><%= contact.lat %></td>
        <td class="lng"><%= contact.lng %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

<div id="map"></div>

<script>
  let map;
  let geocoder;
</script>

<%= render partial: 'shared/maps' %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

<%= render partial: 'shared/maps' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @contact.cpf %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact.phone_number %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @contact.cep %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @contact.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @contact.lng %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerenciador de Contatos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if current_user %>
        Logado como: <%= current_user.email %>
        <%= link_to "Sair", logout_path %>
        <%= link_to 'Excluir conta', delete_users_path %>
      <% else %>
        <%= link_to "Criar conta", signup_path %> ou
        <%= link_to "Entrar", login_path %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h2>Informe uma nova senha:</h2>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
  <div class="field">
    <%= form.label :password, "senha" %>
    <%= form.password_field :password %>
  </div>
  <div class="field">
    <%= form.label :password_confirmation, "confirmação de senha" %>
    <%= form.password_field :password_confirmation %>
  </div>
  <%= form.submit 'Redefinir senha' %>
<%end%>

app/views/password_resets/new.html.erb
<h2>Esqueceu sua senha?</h2>
<%= form_with url: password_reset_path do |form| %>
    <%= form.label :email_address, "E-mail" %>
    <%= form.text_field :email_address %>
    <%= form.submit 'Redefinir senha' %>
<%end%>

app/views/shared/_maps.html.erb
<!-- Import do mapa -->
<script>(g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})
        ({key: "<%= ENV['GOOGLE_MAPS_API_KEY'] %>", v: "weekly"});</script>

<!-- Configs do mapa: -->
<script>
  // let map;
  // let geocoder;

  async function initMap() {
    const { Map } = await google.maps.importLibrary("maps");
    geocoder = new google.maps.Geocoder();

    <% if action_name == 'index' %>
      map = new Map(document.getElementById("map"), {
        center: { lat: -25.432636, lng: -49.266255 },
        zoom: 10,
      });
    <% end %>

    <% if @contacts %>
      <% @contacts.each do |c| %>
        new google.maps.Marker({
          position: { lat: <%= c.lat.to_f %>, lng: <%= c.lng.to_f %> },
          map,
          title: "<%= c.name %>",
        });  
      <% end %>
    <% end %>
  }

  <% if action_name == 'new' %>
    function codeAddress() {
      var address = document.getElementById('contact_address').value;
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == 'OK') {
          let inputLat = document.getElementById('contact_lat');
          let inputLng = document.getElementById('contact_lng');

          var latLng = JSON.stringify(results[0].geometry.location);

          var regex = /"lat"\s*:\s*(-?\d+\.\d+),\s*"lng"\s*:\s*(-?\d+\.\d+)/;

          var match = regex.exec(latLng);

          if (match !== null) {
              var lat = parseFloat(match[1]);
              var lng = parseFloat(match[2]);
                  

          inputLat.value = lat;
          inputLng.value = lng;
          }
        } else {
          alert('Geocode was not successful for the following reason: ' + status);
        }
      });
    }
  <% end %>

  initMap();
</script>

<% if action_name == 'index' %>
  <script>
    function moveMapToPosition(lat, lng) {
      var newPosition = new google.maps.LatLng(lat, lng);
      map.panTo(newPosition);
      //marker.setPosition(newPosition);
      map.setZoom(15);
    }

    var contactsList = document.getElementById("contacts");
    contactsList.addEventListener("click", function(event) {
      if (event.target.tagName === "A") {
        moveMapToPosition(event.target.dataset.lat, event.target.dataset.lng);
      }
    })
  </script>
<% end %>

app/views/users/delete.html.erb
<%= form_tag(destroy_users_path) do %>
  <%= label_tag :password, "Digite sua senha:" %>
  <%= password_field_tag :password %>
  <%= submit_tag "Confirmar exclusão", data: { confirm: "Tem certeza que deseja excluir sua conta?" } %>
<% end %>

app/views/users/new.html.erb
<h1>Criar conta</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password, "Senha" %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, "Confirme a senha" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Registrar" %>
  </div>
<% end %>